server.port=8081
spring.datasource.url=jdbc:oracle:thin:@o9w6nclr7cunlhml_high?TNS_ADMIN=src/main/resources/Wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=FullStack2025
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
