server.port=8080

# Configuración de la base de datos Oracle
spring.datasource.url=jdbc:oracle:thin:@o9w6nclr7cunlhml_high?TNS_ADMIN=C:/Users/israe/OneDrive/Escritorio/proyecto_full_stack/proyecto_springboot_final/microservicio-usuario/EcoMarket/src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=FullStack2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# Dialecto de Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

